const content = {
    en: {
        title: 'The Grand Egyptian Museum: Treasures of the Nile',
        nav: { home: 'Home', about: 'About', exhibits: 'Exhibits', discoveries: 'Discoveries', contact: 'Contact' },
        home: {
            hero_title: 'Unearthing History.',
            hero_subtitle: 'Preserving Legacy.',
            hero_tagline: 'Explore the wonders of over 7000 years of civilization, standing at the gates of the Pyramids.',
            cta: 'Plan Your Visit',
            motto: 'Where Eternity Begins.',
            expertise_title: 'Core Archaeological Themes',
            exp1_title: 'Ancient Architecture', exp1_text: 'The structural genius of the Old Kingdom, from pyramids to temples.',
            exp2_title: 'Funerary Art', exp2_text: 'Intricate details of burial rites, sarcophagi, and the journey to the afterlife.',
            exp3_title: 'Script & Language', exp3_text: 'Deciphering Hieroglyphs, Demotic script, and the language of the Pharaohs.',
            testimonials_title: 'Visitor Acclaim',
            test1_quote: '"The sheer scale of the exhibits is breathtaking. Seeing the colossal statue of Ramesses II in the lobby is an experience I will never forget."',
            test1_client: '— Sarah M., Historian, London',
            test2_quote: '"The Tutankhamun collection is displayed perfectly. The way they utilize light and space makes every piece feel alive."',
            test2_client: '— Dr. Ayman K., Archaeologist, Cairo',
        },
        about: {
            title: 'Our Mission & Vision',
            background_heading: 'Guardians of a Golden Era',
            background_p1: 'The Grand Egyptian Museum (GEM) is a monument dedicated to preserving and exhibiting the treasures of ancient Egypt. Located on the Giza Plateau, it serves as the custodian of humanity\'s rich past, connecting modern scholarship with ancient wonders.',
            background_p2: 'Our vision is to be the leading global center for Egyptian studies, employing the latest conservation technologies and offering an immersive, educational journey for all visitors.',
            values_heading: 'Core Museum Values',
            value1_title: 'Preservation', value1_text: 'Commitment to the long-term conservation of every artifact.',
            value2_title: 'Education', value2_text: 'Fostering understanding and appreciation for Egyptian history worldwide.',
            value3_title: 'Innovation', value3_text: 'Using cutting-edge technology for display and research.',
            team_heading: 'Our Curatorial Team',
            att1_name: 'Dr. Fatima El-Sayed', att1_role: 'Chief Curator, Old Kingdom', att1_focus: 'Specializes in architecture and pyramid construction.',
            att2_name: 'Professor Zaki Abbas', att2_role: 'Head of Conservation', att2_focus: 'Expert in textile, wood, and gold restoration.',
            att3_name: 'Leila Hassan', att3_role: 'Artifacts Specialist, Luxor', att3_focus: 'Focuses on temple murals and New Kingdom funerary objects.',
            att4_name: 'Khaled Mansour', att4_role: 'Researcher, Epigraphy', att4_focus: 'Handles translation and cataloging of stele and scrolls.'
        },
        exhibits: {
            title: 'Core Collections and Artifacts',
            tagline: 'We offer a comprehensive journey through dynastic history, with a special focus on the complete collection of King Tutankhamun.',
            s1_title: 'The Great Pyramid of Giza (Khufu)', s1_p: 'Explore the structural genius behind the largest pyramid ever built, focusing on internal chambers and construction techniques.', s1_l1: 'Pharaonic Architecture', s1_l2: 'The Solar Boat', s1_l3: 'Pyramid Builders\' Town',
            s2_title: 'Mask of Tutankhamun', s2_p: 'The iconic funerary mask and its associated burial chamber treasures, displayed in their entirety for the first time.', s2_l1: 'King Tut\'s Sarcophagus', s2_l2: 'Canopic Shrines', s2_l3: 'Royal Gold Jewelry',
            s3_title: 'The Temple of Karnak', s3_p: 'A massive complex dedicated to the Theban Triad. Our exhibit focuses on the Great Hypostyle Hall and the religious life of Ancient Thebes.', s3_l1: 'Amun-Ra Cult artifacts', s3_l2: 'Obelisks and Statuary', s3_l3: 'Festival of Opet Recreations',
            s4_title: 'Rosetta Stone & Epigraphy', s4_p: 'Discover the key to deciphering ancient Egyptian scripts, alongside interactive displays of hieroglyphs and Demotic writing.', s4_l1: 'Scribal Tools and Papyrus', s4_l2: 'Ptolemaic Decrees', s4_l3: 'The World of Jean-François Champollion',
        },
        discoveries: {
            title: 'Landmark Moments in Egyptology',
            tagline: 'Critical moments that shaped modern understanding of Ancient Egypt, presented through original field notes and reconstructions.',
            note: 'These exhibits include interactive digital displays and replicas for educational purposes.',
            c1_area: 'Discovery / Tomb KV62', c1_title: 'The Finding of Tutankhamun', c1_text: 'The dramatic $1922$ discovery by Howard Carter and the staggering $5,000$ items found within the intact tomb.',
            c2_area: 'Epigraphy / Translation', c2_title: 'The Rosetta Revelation', c2_text: 'How the trilingual stone provided the crucial key, unlocking thousands of years of Egyptian history for modern scholars.',
            c3_area: 'Site Excavation', c3_title: 'The Abu Simbel Salvage', c3_text: 'The monumental international effort to dismantle and relocate the temples of Ramesses II and Nefertari to save them from rising waters.',
            c4_area: 'Theories / Construction', c4_title: 'How the Pyramids were Built', c4_text: 'Latest research on the construction methods, labor organization, and logistics behind the massive Giza structures.',
            c5_area: 'Historical Figures', c5_title: 'The Reign of Ramesses II', c5_text: 'A deep dive into the life, battles, and architectural legacy of Egypt\'s most celebrated pharaoh, Ramesses the Great.',
            c6_area: 'Conservation', c6_title: 'Preserving the Mummies', c6_text: 'The science and art of mummification and the modern conservation techniques used to protect royal remains.',
        },
        contact: {
            title: 'Plan Your Visit & Contact',
            form_heading: 'Inquiry Form',
            name_label: 'Full Name', email_label: 'Email Address', subject_label: 'Subject / Inquiry Type', message_label: 'Brief Description of Inquiry',
            submit_button: 'Send Inquiry',
            form_success: 'Inquiry submitted. A museum representative will contact you within 48 hours.',
            location_heading: 'Museum Location (Giza Plateau)',
            address_line1: 'The Grand Egyptian Museum (GEM)', address_line2: 'New Administrative Capital Road, Giza, Cairo, Egypt',
            map_placeholder: 'Interactive Google Map centered on the Museum.',
            direct_heading: 'Direct Contact',
            phone_label: 'Phone:', email_label_direct: 'Email:',
            phone_number: '+20 (2) 123-9999', email_address: 'info@gem.eg.com',
        }
    },
    ar: {
        title: 'المتحف المصري الكبير: كنوز النيل',
        nav: { home: 'الرئيسية', about: 'عن المتحف', exhibits: 'المعروضات', discoveries: 'الاكتشافات', contact: 'اتصل بنا' },
        home: {
            hero_title: 'الكشف عن التاريخ.',
            hero_subtitle: 'حفظ الإرث.',
            hero_tagline: 'استكشف عجائب أكثر من 7000 سنة من الحضارة، وتقف عند بوابات الأهرامات.',
            cta: 'خطط لزيارتك',
            motto: 'حيث تبدأ الأبدية.',
            expertise_title: 'المحاور الأثرية الأساسية',
            exp1_title: 'الهندسة المعمارية القديمة', exp1_text: 'عبقرية الهيكل في المملكة القديمة، من الأهرامات إلى المعابد.',
            exp2_title: 'الفن الجنائزي', exp2_text: 'تفاصيل معقدة لطقوس الدفن والتوابيت والرحلة إلى الحياة الأخرى.',
            exp3_title: 'الخط واللغة', exp3_text: 'فك رموز الهيروغليفية والخط الديموطيقي ولغة الفراعنة.',
            testimonials_title: 'ثناء الزوار',
            test1_quote: '"الحجم الهائل للمعارض يخطف الأنفاس. رؤية تمثال رمسيس الثاني الضخم في الردهة هي تجربة لن أنساها أبدًا."',
            test1_client: '— سارة م.، مؤرخة، لندن',
            test2_quote: '"مجموعة توت عنخ آمون معروضة بشكل مثالي. الطريقة التي يستخدمون بها الضوء والمساحة تجعل كل قطعة تبدو حية."',
            test2_client: '— د. أيمن ك.، عالم آثار، القاهرة',
        },
        about: {
            title: 'رسالتنا ورؤيتنا',
            background_heading: 'حراس العصر الذهبي',
            background_p1: 'يعد المتحف المصري الكبير (GEM) صرحًا مخصصًا للحفاظ على كنوز مصر القديمة وعرضها. يقع المتحف في هضبة الجيزة، ويعمل كوصي على ماضي البشرية الغني، ويربط بين المنح الدراسية الحديثة والعجائب القديمة.',
            background_p2: 'تتمثل رؤيتنا في أن نكون المركز العالمي الرائد للدراسات المصرية، باستخدام أحدث تقنيات الحفظ وتقديم رحلة تعليمية غامرة لجميع الزوار.',
            values_heading: 'القيم الأساسية للمتحف',
            value1_title: 'الحفظ', value1_text: 'الالتزام بالحفظ طويل الأمد لكل قطعة أثرية.',
            value2_title: 'التعليم', value2_text: 'تعزيز الفهم والتقدير للتاريخ المصري في جميع أنحاء العالم.',
            value3_title: 'الابتكار', value3_text: 'استخدام التكنولوجيا المتطورة للعرض والبحث.',
            team_heading: 'فريقنا الإشرافي',
            att1_name: 'د. فاطمة السيد', att1_role: 'كبير الأمناء، المملكة القديمة', att1_focus: 'متخصصة في الهندسة المعمارية وبناء الأهرامات.',
            att2_name: 'أ. زكي عباس', att2_role: 'رئيس قسم الحفظ', att2_focus: 'خبير في ترميم المنسوجات والخشب والذهب.',
            att3_name: 'ليلى حسن', att3_role: 'أخصائي آثار، الأقصر', att3_focus: 'تركز على لوحات المعابد ومقتنيات الدفن في المملكة الحديثة.',
            att4_name: 'خالد منصور', att4_role: 'باحث، النقوش', att4_focus: 'يتولى ترجمة وفهرسة المسلات والمخطوطات.',
        },
        exhibits: {
            title: 'المجموعات والآثار الأساسية',
            tagline: 'نقدم رحلة شاملة عبر التاريخ الأسري، مع تركيز خاص على المجموعة الكاملة للملك توت عنخ آمون.',
            s1_title: 'هرم خوفو الأكبر', s1_p: 'استكشف العبقرية الهيكلية وراء أكبر هرم تم بناؤه على الإطلاق، مع التركيز على الغرف الداخلية وتقنيات البناء.', s1_l1: 'العمارة الفرعونية', s1_l2: 'مركب الشمس', s1_l3: 'مدينة بناة الأهرامات',
            s2_title: 'قناع توت عنخ آمون', s2_p: 'القناع الجنائزي الأيقوني وكنوز غرفة دفنه المرتبطة به، معروضة بالكامل لأول مرة.', s2_l1: 'تابوت الملك توت', s2_l2: 'المقاصير الكانوبية', s2_l3: 'المجوهرات الذهبية الملكية',
            s3_title: 'معبد الكرنك', s3_p: 'مجمع ضخم مخصص لثالوث طيبة. يركز معرضنا على قاعة الأعمدة الكبرى والحياة الدينية في طيبة القديمة.', s3_l1: 'آثار عبادة آمون رع', s3_l2: 'المسلات والتماثيل', s3_l3: 'إعادة إنشاء احتفالات الأوبت',
            s4_title: 'حجر رشيد وعلم النقوش', s4_p: 'اكتشف مفتاح فك رموز الكتابات المصرية القديمة، إلى جانب عروض تفاعلية للهيروغليفية والكتابة الديموطيقية.', s4_l1: 'أدوات الكتبة وورق البردي', s4_l2: 'المراسيم البطلمية', s4_l3: 'عالم جان فرانسوا شامبليون',
        },
        discoveries: {
            title: 'لحظات فارقة في علم المصريات',
            tagline: 'لحظات حاسمة شكلت الفهم الحديث لمصر القديمة، معروضة من خلال الملاحظات الميدانية الأصلية وإعادة البناء.',
            note: 'تتضمن هذه المعروضات شاشات رقمية تفاعلية ونسخًا طبق الأصل للأغراض التعليمية.',
            c1_area: 'اكتشاف / مقبرة KV62', c1_title: 'العثور على توت عنخ آمون', c1_text: 'الاكتشاف المذهل الذي قام به هوارد كارتر عام $1922$ والـ $5000$ قطعة مذهلة التي وُجدت داخل المقبرة السليمة.',
            c2_area: 'النقوش / الترجمة', c2_title: 'وحي حجر رشيد', c2_text: 'كيف قدم الحجر ثلاثي اللغة المفتاح الحاسم، ليفتح آلاف السنين من التاريخ المصري أمام العلماء المعاصرين.',
            c3_area: 'التنقيب في الموقع', c3_title: 'إنقاذ أبو سمبل', c3_text: 'الجهد الدولي الضخم لتفكيك ونقل معابد رمسيس الثاني ونفرتاري لإنقاذها من ارتفاع منسوب المياه.',
            c4_area: 'نظريات / البناء', c4_title: 'كيف بُنيت الأهرامات', c4_text: 'أحدث الأبحاث حول طرق البناء وتنظيم العمل واللوجستيات وراء هياكل الجيزة الضخمة.',
            c5_area: 'شخصيات تاريخية', c5_title: 'عهد رمسيس الثاني', c5_text: 'تعمق في حياة ومعارك وإرث مصر المعماري لأشهر الفراعنة، رمسيس العظيم.',
            c6_area: 'الحفظ', c6_title: 'الحفاظ على المومياوات', c6_text: 'علم وفن التحنيط وتقنيات الحفظ الحديثة المستخدمة لحماية الرفات الملكية.',
        },
        contact: {
            title: 'خطط لزيارتك وتواصل معنا',
            form_heading: 'نموذج الاستفسار',
            name_label: 'الاسم الكامل', email_label: 'البريد الإلكتروني', subject_label: 'الموضوع / نوع الاستفسار', message_label: 'وصف موجز للاستفسار',
            submit_button: 'إرسال الاستفسار',
            form_success: 'تم إرسال استفسارك. سيتصل بك ممثل للمتحف في غضون 48 ساعة.',
            location_heading: 'موقع المتحف (هضبة الجيزة)',
            address_line1: 'المتحف المصري الكبير (GEM)', address_line2: 'طريق العاصمة الإدارية الجديدة، الجيزة، القاهرة، مصر',
            map_placeholder: 'خريطة جوجل التفاعلية المتمركزة على المتحف.',
            direct_heading: 'الاتصال المباشر',
            phone_label: 'الهاتف:', email_label_direct: 'البريد الإلكتروني:',
            phone_number: '+20 (2) 123-9999', email_address: 'info@gem.eg.com',
        }
    }
};
